project:
  type: default
  output-dir: outputs
  render:
    - "paper.qmd"
    - "truth-post/index.qmd"
    - "truth-post/blueprint/index.qmd"
    - "rpgf/index.qmd"
    - "rpgf/design/index.qmd"

date-format: "MMMM D, YYYY [at] HH:mm"

format:
  html:
    output-file: index
    embed-resources: false
    css: fonts.css
    include-after-body: figure-theme-swap.html
    theme:
      light: [flatly, custom-light.scss]
      dark: [darkly, custom-dark.scss]
    respect-user-color-scheme: true
    page-layout: article
    grid:
      body-width: 780px
      margin-width: 220px
      gutter-width: 1.75rem
    toc: true
    toc-location: left
    toc-title: Contents
    toc-depth: 2
    toc-expand: 1
    number-sections: true
    anchor-sections: true
    html-math-method: katex
  pdf:
    output-file: paper
    toc: true
    toc-depth: 3
    number-sections: true

bibliography: references.bib

resources:
  - analysis/fig/*-dark.png
  - diagrams/fig-*-dark.png
