project:
  type: default
  output-dir: outputs
  render:
    - "paper.qmd"

format:
  html:
    output-file: paper
    embed-resources: true
    theme: darkly
    css: styles.css
    page-layout: article
    grid:
      body-width: 820px
      margin-width: 300px
      gutter-width: 1.5rem
    toc: true
    toc-depth: 3
    number-sections: true
    anchor-sections: true
    html-math-method: katex
  pdf:
    output-file: paper
    toc: true
    toc-depth: 3
    number-sections: true
  docx:
    output-file: paper
    toc: true
    toc-depth: 3
    number-sections: true

bibliography: references.bib

